server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/video_applet?characterEncoding=utf8&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379

  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

  jpa:
    show-sql: true

