#服务名称
server:
  port: 5001

#连接配置信息
spring:
  application:
    name: config-server-jdbc
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        default-label: dev
        jdbc:
          sql: SELECT akey , avalue FROM config_server where APPLICATION=? and APROFILE=? and LABEL=?
  #####################################################################################################
  # mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/config
    username: root
    password: 123456
#####################################################################################################


#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

