server:
    port: 8080
netty:
    server:
        port: 8092

##配置c3p0连接池信息
c3p0:
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/chat?characterEncoding=utf8&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    userName: root
    password: root
    initialPoolSize: 10
    maxIdleTime: 30 #最大空闲时间,多少秒内未使用则连接被丢弃。若为0则永不丢弃。Default: 0
    maxPoolSize: 100 #连接池中保留的最大连接数。Default: 15
    minPoolSize: 10 #最小连接数

